<a href="https://colab.research.google.com/github/robertbarac/Notas_Numpy_Pandas_Matplotlib_Y_Seaborn/blob/main/numpy_y_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Array** 
*Operaciones básicas con vectores*

In [ ]:
import numpy as np

In [ ]:
lista = [i+1 for i in range(9)]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[0]

1

In [ ]:
matriz[0]

array([1, 2, 3])

In [ ]:
matriz[0][2]

3

In [ ]:
arr[0] + arr[4]

6

In [ ]:
matriz[0,2]

3

In [ ]:
arr[:3]

array([1, 2, 3])

In [ ]:
arr[::2]

array([1, 3, 5, 7, 9])

In [ ]:
arr[::3]

array([1, 4, 7])

In [ ]:
arr[-1:]

array([9])

In [ ]:
arr[-1]

9

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
# Arreglo 3D
m3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
m3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
m3d[1:,0:2,:2]

array([[[10, 11],
        [13, 14]],

       [[19, 20],
        [22, 23]]])

#3-Tipos de Datos

In [ ]:
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [ ]:
array.dtype

dtype('int64')

In [ ]:
type(array)

numpy.ndarray

In [ ]:
array = np.array([0,1,2,3,4], dtype='float64')
array

array([0., 1., 2., 3., 4.])

In [ ]:
array = array.astype(np.float64)

In [ ]:
array

array([0., 1., 2., 3., 4.])

In [ ]:
array.astype(np.bool_)

array([False,  True,  True,  True,  True])

In [ ]:
array.astype(np.string_)

array([b'0.0', b'1.0', b'2.0', b'3.0', b'4.0'], dtype='|S32')

In [ ]:
array.astype(np.int8)

array([0, 1, 2, 3, 4], dtype=int8)

#4-Dimensiones en Arrays

In [ ]:
scalar = np.array(42)
scalar

array(42)

In [ ]:
scalar.ndim

0

In [ ]:
scalar1d = np.array([1,2,3])
scalar1d.ndim

1

In [ ]:
scalar2d = np.array([[1,2,3],[4,5,6]])
scalar2d.ndim

2

In [ ]:
m3d.ndim

NameError: ignored

**Y así sucesivamente...**

#Agregar o eliminar dimensiones...

In [ ]:
vector=np.array([1,2,3],ndmin=10)
vector

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [ ]:
vector.ndim

10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0) # 0 en axis es filas, 1 es columnas
expand.ndim # np.expand_dims aumenta la dimensión en 1.

2

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) # El método np.squeeze lo lleva a la dimensionalidad correcta
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


#Creando Arrays

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
from numpy.core.function_base import linspace
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(4) # Matriz identidad

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand()

0.9350091724272315

In [ ]:
np.random.rand(4)

array([0.85516497, 0.73474778, 0.74124801, 0.42413422])

In [ ]:
np.random.rand(4,4)

array([[0.28429276, 0.10434839, 0.40361852, 0.84733255],
       [0.62545267, 0.04549126, 0.62398255, 0.90233334],
       [0.90041774, 0.06327094, 0.15044535, 0.35099696],
       [0.28319501, 0.13351683, 0.80864011, 0.91825675]])

In [ ]:
np.random.rand(3,3,3)

array([[[0.75355907, 0.35968175, 0.16880053],
        [0.5668844 , 0.3841228 , 0.03886672],
        [0.35841546, 0.94067502, 0.11291126]],

       [[0.25154839, 0.67529293, 0.00927349],
        [0.11636924, 0.09855821, 0.65134437],
        [0.85204433, 0.35702115, 0.15153011]],

       [[0.05532465, 0.06180944, 0.22872759],
        [0.4900947 , 0.61749676, 0.97866786],
        [0.17854896, 0.68192353, 0.30954786]]])

In [ ]:
np.random.randint(1,15)

11

In [ ]:
a = np.random.randint(1,100,(10,10))
a

array([[61, 12, 47, 99, 82, 80, 91,  3, 54,  8],
       [84, 40, 75, 70, 38, 91, 61,  1,  8, 53],
       [86, 75, 31, 71, 51, 18, 91,  5, 76, 35],
       [90, 97, 80, 48, 95, 85, 26, 40, 95, 80],
       [ 2, 10,  5, 47,  8, 77, 86, 94, 23, 99],
       [61, 36, 67, 11, 16, 35, 52, 62, 51, 63],
       [42, 44, 97, 68, 99, 59, 20, 74, 61, 84],
       [16,  7, 22, 77, 47, 95, 57, 49, 62, 94],
       [47, 55, 38,  1, 99, 74,  7, 72, 39, 91],
       [60, 31,  1, 25, 86, 19, 29, 77, 44, 92]])

In [ ]:
a.ndim

2

#6-Shape y Reshape

In [ ]:
a = np.random.randint(1,10,(3,2))
a

array([[7, 9],
       [6, 7],
       [8, 1]])

In [ ]:
a.shape

(3, 2)

In [ ]:
a.reshape(1,6)

array([[7, 9, 6, 7, 8, 1]])

In [ ]:
a.reshape(2,3)

array([[7, 9, 6],
       [7, 8, 1]])

In [ ]:
np.reshape(a,(1,6))

array([[7, 9, 6, 7, 8, 1]])

In [ ]:
a

array([[7, 9],
       [6, 7],
       [8, 1]])

In [ ]:
np.reshape(a, (2,3), 'C')

array([[7, 9, 6],
       [7, 8, 1]])

In [ ]:
np.reshape(a, (2,3), 'F')

array([[7, 8, 7],
       [6, 9, 1]])

In [ ]:
np.reshape(a, (2,3), 'A')

array([[7, 9, 6],
       [7, 8, 1]])

# 7-Funciones principales de Numpy

In [ ]:
arr = np.random.randint(1,20,10)
arr

array([18,  1, 15, 18, 17,  8, 13, 17,  2, 17])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[18,  1, 15, 18, 17],
       [ 8, 13, 17,  2, 17]])

In [ ]:
arr.max() # el mayor dato del array...

18

In [ ]:
matriz.max()

18

In [ ]:
matriz.max(1) #Sacar el mayor valor por fila

array([18, 17])

In [ ]:
matriz.max(0) #Sacar el mayor valor por columna

array([18, 13, 17, 18, 17])

In [ ]:
arr.argmax(0) #Índice donde se encuentra el valor más grande

0

In [ ]:
matriz

array([[18,  1, 15, 18, 17],
       [ 8, 13, 17,  2, 17]])

In [ ]:
matriz.argmax(0)

array([0, 1, 1, 0, 0])

In [ ]:
arr.min()

1

In [ ]:
matriz.min()

1

In [ ]:
matriz.min(0)

array([ 8,  1, 15,  2, 17])

In [ ]:
matriz.min(1)

array([1, 2])

In [ ]:
arr.argmin()

1

In [ ]:
matriz.argmin(0)

array([1, 0, 0, 1, 0])

In [ ]:
matriz.argmin(1)

array([1, 3])

In [ ]:
arr.ptp() # Diferencia entre el valor más alto y más bajo del array

17

In [ ]:
matriz.ptp(0)

array([10, 12,  2, 16,  0])

In [ ]:
matriz.ptp(1)

array([17, 15])

In [ ]:
np.percentile(arr, 50)

16.0

In [ ]:
arr.sort()

In [ ]:
arr

array([ 1,  2,  8, 13, 15, 17, 17, 17, 18, 18])

In [ ]:
np.percentile(arr,50)

16.0

In [ ]:
np.median(arr)

16.0

**Vemos que la mediana coincide con el percentil 50**

In [ ]:
np.median(arr,0)

16.0

In [ ]:
np.median(matriz,1)

array([ 8., 17.])

In [ ]:
np.median(matriz,0)

array([ 9. ,  9.5, 12.5, 15.5, 16.5])

In [ ]:
np.std(arr)

6.248199740725324

In [ ]:
np.std(arr)**2

39.040000000000006

In [ ]:
np.var(arr)

39.040000000000006

In [ ]:
np.mean(arr)

12.6

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([5,6])

In [ ]:
c = np.concatenate((a,b), axis=0)
c

ValueError: ignored

In [ ]:
print(a.ndim, b.ndim)

2 1


In [ ]:
b = np.expand_dims(b, axis=0)
b

array([[5, 6]])

In [ ]:
c = np.concatenate((a,b), axis=0) # Ahora sí sale...
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
d = np.concatenate((a,b), axis=1)
d

ValueError: ignored

In [ ]:
d = np.concatenate((a,b.T), axis=1)
d

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
b.T # Matriz trasspuesta

array([[5],
       [6]])

#8-Copy

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

**Arreglémoslo...**

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100

In [ ]:
print(arr, arr_copy) # He ahí la diferencia...

[ 0  1  2  3  4  5  6  7  8  9 10] [100 100 100 100 100 100 100 100 100 100 100]


#9-Condicionales

In [ ]:
ar = np.linspace(1,10,10, dtype='int8')
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
ar > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
ar[(ar > 5) & (ar < 9)]

array([6, 7, 8], dtype=int8)

In [ ]:
ar[ar>5]=99

In [ ]:
ar

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [ ]:
ar[ar==99]

array([99, 99, 99, 99, 99], dtype=int8)

#10-Operaciones

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista*2

[1, 2, 1, 2]

In [ ]:
array=np.array(lista)
array

array([1, 2])

In [ ]:
array_por_dos = array*2
array_por_dos

array([2, 4])

In [ ]:
1/array

array([1. , 0.5])

In [ ]:
array + array_por_dos #La suma es uno a uno, índice con su índice respectivo, array a array

array([3, 6])

In [ ]:
array*array_por_dos

array([2, 8])

In [ ]:
matriz = np.array([array, array_por_dos])
matriz.ndim

2

In [ ]:
matriz2 = (matriz*3).copy()
print(matriz)
print(matriz2)

[[1 2]
 [2 4]]
[[ 3  6]
 [ 6 12]]


In [ ]:
matriz

array([[1, 2],
       [2, 4]])

In [ ]:
matriz2

array([[ 3,  6],
       [ 6, 12]])

In [ ]:
matriz_resta = matriz - matriz2
matriz_resta

array([[-2, -4],
       [-4, -8]])

In [ ]:
np.matmul(matriz, matriz2.T)

array([[15, 30],
       [30, 60]])

In [ ]:
np.matmul(matriz, matriz2)

array([[15, 30],
       [30, 60]])

In [ ]:
matriz @ matriz2

array([[15, 30],
       [30, 60]])

In [ ]:
matriz @ matriz2.T

array([[15, 30],
       [30, 60]])

#11 - Series y DataFrames en Pandas

In [ ]:
import pandas as pd

In [ ]:
psg_players = pd.Series(['Navas', 'Mbappe', 'Neymar', 'Messi'],
          index=[1, 7, 10, 30]
          )
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
pd.Series(['Navas', 'Mbappe', 'Neymar', 'Messi'])

0     Navas
1    Mbappe
2    Neymar
3     Messi
dtype: object

In [ ]:
#Convertir diccionario a un objeto de tipo Series de Pandas
dictt = {1:'Navas', 7:'Mbappe', 10:'Neymar', 30:'Messi'}
pd.Series(dictt)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
psg_players[30]

'Messi'

In [ ]:
psg_players[0:3]

1      Navas
7     Mbappe
10    Neymar
dtype: object

In [ ]:
dict_psg_players = {'Jugador':['Navas', 'Mbappe', 'Neymar', 'Messi'],
 'Altura':[183.0, 170.0, 170.0, 165.0],
 'Goles':[2, 200, 200, 700]
 }

In [ ]:
pd.DataFrame(dict_psg_players, index=[1, 7, 10, 30])

Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    200
30   Messi   165.0    700

In [ ]:
df_players = pd.DataFrame(dict_psg_players)
df_players

Jugador  Altura  Goles
0   Navas   183.0      2
1  Mbappe   170.0    200
2  Neymar   170.0    200
3   Messi   165.0    700

In [ ]:
df_players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [ ]:
df_players.index

RangeIndex(start=0, stop=4, step=1)

#12 - Leer archivos CSV y JSON con Pandas

In [ ]:
df_books = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Basico Pandas y Numpy/db/bestsellers-with-categories.csv')
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [ ]:
df_books.index

RangeIndex(start=0, stop=550, step=1)

In [ ]:
pd.read_json('/content/drive/MyDrive/Colab Notebooks/Basico Pandas y Numpy/db/hpcharactersdataraw.json', typ='Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

In [ ]:
df_harry_potter = pd.read_json('/content/drive/MyDrive/Colab Notebooks/Basico Pandas y Numpy/db/hpcharactersdataraw.json')
df_harry_potter

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

#13 - Filtrado don loc y iloc

In [ ]:
df_books[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [ ]:
df_books['Name']

0                          10-Day Green Smoothie Cleanse
1                                      11/22/63: A Novel
2                12 Rules for Life: An Antidote to Chaos
3                                 1984 (Signet Classics)
4      5,000 Awesome Facts (About Everything!) (Natio...
                             ...                        
545         Wrecking Ball (Diary of a Wimpy Kid Book 14)
546    You Are a Badass: How to Stop Doubting Your Gr...
547    You Are a Badass: How to Stop Doubting Your Gr...
548    You Are a Badass: How to Stop Doubting Your Gr...
549    You Are a Badass: How to Stop Doubting Your Gr...
Name: Name, Length: 550, dtype: object

In [ ]:
df_books[['Name', 'Author']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  
0                    JJ Smith  
1                Stephen King  
2          Jordan B. Peterson  
3               George Orwell  
4    National Geographic Kids  
..                        ...  
545               Jeff Kinney  
546               Jen Sincero  
547               Jen Sincero  
548               Jen Sincero  
549               Jen Sincero  

[550 rows x 2 columns]

In [ ]:
df_books[['Name', 'Author', 'Year']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  Year  
0                    JJ Smith  2016  
1                Stephen King  2011  
2          Jordan B. Peterson  2018  
3               George Orwell  2017  
4    National Geographic Kids  2019  
..                        ...   ...  
545               Jeff Kinney  2019  
546               Jen Sincero  2016  
547               Jen Sincero  2017  
548               Jen Sincero  2018  
549               Jen Sincero  2019  

[550 rows x 3 columns]

In [ ]:
#Loc: 
df_books.loc[:] #Está mostrando todo el dataframe

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.loc[0:4] #Está mostrando algo similar a df_books[0:4] pero incluyendo el índice 4

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [ ]:
df_books.loc[0:4, ['Name', 'Author']] # De la 0 a la 4 por nombre y autor

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [ ]:
df_books.loc[:, ['Reviews']]*-1 #Toma todos los valores de la columna reviews, los multiplica por -1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [ ]:
#Registros cuyo autor sea JJ Smith
df_books.loc[:, ['Author']]=='JJ Smith'

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

**OTRA FUNCIÓN ES ILOC**

In [ ]:
df_books.iloc[:] #igual que df_books.loc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
# Aquí se filtra por los índices de las columnas y no por nombres de lascolumnas. Toma las columnas 0, 1 y 2.
# 0 es Name, 1 es Author y 2 es User Rating
df_books.iloc[:, 0:3]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [ ]:
df_books.iloc[1,3]

2052

In [ ]:
df_books.iloc[1,3]*-1

-2052

In [ ]:
df_books.iloc[:2, 2:]

User Rating  Reviews  Price  Year        Genre
0          4.7    17350      8  2016  Non Fiction
1          4.6     2052     22  2011      Fiction

#14 - Agregar o eliminar datos con Pandas

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

**Drop Columns**

In [ ]:
df_books.drop('Genre', axis=1)#.head(2) #0 son filas, 1 son columnas. Se eliminó la columna género

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year  
0                    JJ Smith          4.7    17350      8  2016  
1                Stephen King          4.6     2052     22  2011  
2          Jordan B. Peterson          4.7    18979     15  2018  
3               George Orwell          4.7    21424      6  2017  
4    National Geographic Kids          4.8     7665     12  2019  
..                        ...          ...      ...    ...   ...  
545               Jeff Kinney          4.9     9413      8  2019  
546               Jen Sincero          4.7    14331      8  2016  
547               Jen Sincero          4.7    14331      8  2017  
548               Jen Sincero          4.7    14331      8  2018  
549               Jen Sincero          4.7    14331      8  2019  

[550 rows x 6 columns]

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [ ]:
df_books.drop('Genre', axis=1, inplace=True)

In [ ]:
df_books.head(2) #Ya no está la columna género porque el código de arriba lo hace efectivo

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [ ]:
df_books = df_books.drop('Year', axis=1)

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8
1              11/22/63: A Novel  Stephen King          4.6     2052     22

In [ ]:
del df_books['Price']

**Borrar Filas**

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350
1              11/22/63: A Novel  Stephen King          4.6     2052

In [ ]:
df_books.drop(0, axis=0).head(2)

Name              Author  User Rating  \
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  
1     2052  
2    18979

In [ ]:
df_books.drop([0,1,2], axis=0).head(2)

Name  \
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  
3             George Orwell          4.7    21424  
4  National Geographic Kids          4.8     7665

In [ ]:
df_books.drop(range(0,10), axis=0).head(2)

Name            Author  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   

    User Rating  Reviews  
10          4.6    23848  
11          4.6      460

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350
1              11/22/63: A Novel  Stephen King          4.6     2052

**Agregar nueva columna**

In [ ]:
df_books['Nueva Columna'] = np.nan
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Nueva Columna  
0                    JJ Smith          4.7    17350            NaN  
1                Stephen King          4.6     2052            NaN  
2          Jordan B. Peterson          4.7    18979            NaN  
3               George Orwell          4.7    21424            NaN  
4    National Geographic Kids          4.8     7665            NaN  
..                        ...          ...      ...            ...  
545               Jeff Kinney          4.9     9413            NaN  
546               Jen Sincero          4.7    14331            NaN  
547               Jen Sincero          4.7    14331            NaN  
548               Jen Sincero          4.7    14331            NaN  
549               Jen Sincero          4.7    14331            NaN  

[550 rows x 5 columns]

In [ ]:
df_books.shape

(550, 5)

In [ ]:
data = np.arange(0, df_books.shape[0])
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
df_books['Rango'] = data
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Nueva Columna  Rango  
0                    JJ Smith          4.7    17350            NaN      0  
1                Stephen King          4.6     2052            NaN      1  
2          Jordan B. Peterson          4.7    18979            NaN      2  
3               George Orwell          4.7    21424            NaN      3  
4    National Geographic Kids          4.8     7665            NaN      4  
..                        ...          ...      ...            ...    ...  
545               Jeff Kinney          4.9     9413            NaN    545  
546               Jen Sincero          4.7    14331            NaN    546  
547               Jen Sincero          4.7    14331            NaN    547  
548               Jen Sincero          4.7    14331            NaN    548  
549               Jen Sincero          4.7    14331            NaN    549  

[550 rows x 6 columns]

In [ ]:
#Otra manera:
df_books.append(df_books)

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Nueva Columna  Rango  
0                    JJ Smith          4.7    17350            NaN      0  
1                Stephen King          4.6     2052            NaN      1  
2          Jordan B. Peterson          4.7    18979            NaN      2  
3               George Orwell          4.7    21424            NaN      3  
4    National Geographic Kids          4.8     7665            NaN      4  
..                        ...          ...      ...            ...    ...  
545               Jeff Kinney          4.9     9413            NaN    545  
546               Jen Sincero          4.7    14331            NaN    546  
547               Jen Sincero          4.7    14331            NaN    547  
548               Jen Sincero          4.7    14331            NaN    548  
549               Jen Sincero          4.7    14331            NaN    549  

[1100 rows x 6 columns]

**Agregar filas**

In [ ]:
df_books.append(df_books)

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Nueva Columna  Rango  
0                    JJ Smith          4.7    17350            NaN      0  
1                Stephen King          4.6     2052            NaN      1  
2          Jordan B. Peterson          4.7    18979            NaN      2  
3               George Orwell          4.7    21424            NaN      3  
4    National Geographic Kids          4.8     7665            NaN      4  
..                        ...          ...      ...            ...    ...  
545               Jeff Kinney          4.9     9413            NaN    545  
546               Jen Sincero          4.7    14331            NaN    546  
547               Jen Sincero          4.7    14331            NaN    547  
548               Jen Sincero          4.7    14331            NaN    548  
549               Jen Sincero          4.7    14331            NaN    549  

[1100 rows x 6 columns]

#15 - Manejo de valores nulos



In [ ]:
dicc = {'Col1':[1, 2, 3, np.nan],
 'Col2':[4, np.nan, 6, 7],
 'Col3':['a', 'b', 'c', None]
 }

In [ ]:
df = pd.DataFrame(dicc)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [ ]:
df.isnull()

Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [ ]:
df.isnull()*1 # Para ponerlos de manera numérica, 1 es True, 0 es False

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [ ]:
df.fillna('Missing')

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [ ]:
df.fillna(df.mean())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [ ]:
df.interpolate()

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [ ]:
df.dropna()

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

#16 - Filtrado por Condiciones

In [ ]:
mayor_a_2016 = df_books['Year']>2016

In [ ]:
df_books[mayor_a_2016] # Muestra los registros cuyo año sean mayores a 2016

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
7                 Amor Towles          4.7    19699     15  2017      Fiction  
8                 James Comey          4.7     5983      3  2018  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
544             R. J. Palacio          4.8    21625      9  2017      Fiction  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[150 rows x 7 columns]

In [ ]:
df_books[df_books['Year']>2016] # La misma forma

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
7                 Amor Towles          4.7    19699     15  2017      Fiction  
8                 James Comey          4.7     5983      3  2018  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
544             R. J. Palacio          4.8    21625      9  2017      Fiction  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[150 rows x 7 columns]

In [ ]:
genre_fiction = df_books['Genre'] == 'Fiction'

In [ ]:
df_books[genre_fiction & mayor_a_2016][20:40]

Name               Author  \
84   Dog Man: Brawl of the Wild: From the Creator o...           Dav Pilkey   
85   Dog Man: Fetch-22: From the Creator of Captain...           Dav Pilkey   
86   Dog Man: For Whom the Ball Rolls: From the Cre...           Dav Pilkey   
87   Dog Man: Lord of the Fleas: From the Creator o...           Dav Pilkey   
97                                  Educated: A Memoir        Tara Westover   
98                                  Educated: A Memoir        Tara Westover   
101                                     Fahrenheit 451         Ray Bradbury   
103                     Fear: Trump in the White House         Bob Woodward   
109        Fire and Fury: Inside the Trump White House        Michael Wolff   
113                                    First 100 Words         Roger Priddy   
114                                    First 100 Words         Roger Priddy   
125                               Giraffes Can't Dance        Giles Andreae   
126                               Giraffes Can't Dance        Giles Andreae   
127                               Giraffes Can't Dance        Giles Andreae   
128  Girl, Stop Apologizing: A Shame-Free Plan for ...        Rachel Hollis   
129  Girl, Wash Your Face: Stop Believing the Lies ...        Rachel Hollis   
130  Girl, Wash Your Face: Stop Believing the Lies ...        Rachel Hollis   
138  Good Days Start With Gratitude: A 52 Week Guid...  Pretty Simple Press   
143                                     Goodnight Moon  Margaret Wise Brown   
144                                     Goodnight Moon  Margaret Wise Brown   

     User Rating  Reviews  Price  Year    Genre  
84           4.9     7235      4  2019  Fiction  
85           4.9    12619      8  2019  Fiction  
86           4.9     9089      8  2019  Fiction  
87           4.9     5470      6  2018  Fiction  
97           4.7    28729     15  2018  Fiction  
98           4.7    28729     15  2019  Fiction  
101          4.6    10721      8  2018  Fiction  
103          4.4     6042      2  2018  Fiction  
109          4.2    13677      6  2018  Fiction  
113          4.7    17323      4  2017  Fiction  
114          4.7    17323      4  2018  Fiction  
125          4.8    14038      4  2017  Fiction  
126          4.8    14038      4  2018  Fiction  
127          4.8    14038      4  2019  Fiction  
128          4.6     7660     12  2019  Fiction  
129          4.6    22288     12  2018  Fiction  
130          4.6    22288     12  2019  Fiction  
138          4.6    10141      6  2019  Fiction  
143          4.8     8837      5  2017  Fiction  
144          4.8     8837      5  2018  Fiction

In [ ]:
df_books[~mayor_a_2016] #Los no mayores a 2016, es genial

Name               Author  \
0                        10-Day Green Smoothie Cleanse             JJ Smith   
1                                    11/22/63: A Novel         Stephen King   
5        A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
9                            A Man Called Ove: A Novel      Fredrik Backman   
..                                                 ...                  ...   
540                                             Wonder        R. J. Palacio   
541                                             Wonder        R. J. Palacio   
542                                             Wonder        R. J. Palacio   
543                                             Wonder        R. J. Palacio   
546  You Are a Badass: How to Stop Doubting Your Gr...          Jen Sincero   

     User Rating  Reviews  Price  Year    Genre  
0            4.7    17350      8  2016  Fiction  
1            4.6     2052     22  2011  Fiction  
5            4.4    12643     11  2011  Fiction  
6            4.7    19735     30  2014  Fiction  
9            4.6    23848      8  2016  Fiction  
..           ...      ...    ...   ...      ...  
540          4.8    21625      9  2013  Fiction  
541          4.8    21625      9  2014  Fiction  
542          4.8    21625      9  2015  Fiction  
543          4.8    21625      9  2016  Fiction  
546          4.7    14331      8  2016  Fiction  

[400 rows x 7 columns]

#17 - Funciones principales de Pandas

****

In [ ]:
df_books.groupby('Genre').size()

Genre
Fiction    550
dtype: int64

In [ ]:
df_books.groupby('Genre').count()

Name  Author  User Rating  Reviews  Price  Year
Genre                                                   
Fiction   550     550          550      550    550   550

In [ ]:
df_books['Genre'].value_counts() # ¿Es lo mismo que lo de arriba?

Fiction    550
Name: Genre, dtype: int64

In [ ]:
df_books['Genre'].count() # ¿Es lo mismo que lo de arriba?

550

In [ ]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [ ]:
df_books.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [ ]:
df_books.describe

<bound method NDFrame.describe of                                                   Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year    Genre  
0                    JJ Smith          4.7    17350      8  2016  Fiction  
1                Stephen King          4.6     2052     22  2011  Fiction  
2          Jordan B. Peterson          4.

In [ ]:
df_books.tail(2)

Name       Author  \
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Price  Year    Genre  
548          4.7    14331      8  2018  Fiction  
549          4.7    14331      8  2019  Fiction

In [ ]:
df_books.memory_usage(deep=True) #Cuánta memoria estoy usando en mi dataframe

Index            128
Name           61267
Author         39212
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          35200
dtype: int64

In [ ]:
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [ ]:
df_books.iloc[0]

Name           10-Day Green Smoothie Cleanse
Author                              JJ Smith
User Rating                              4.7
Reviews                                17350
Price                                      8
Year                                    2016
Genre                                Fiction
Name: 0, dtype: object

In [ ]:
df_books.append(df_books.iloc[0]) # Duplicando el registro 0

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year    Genre  
0                    JJ Smith          4.7    17350      8  2016  Fiction  
1                Stephen King          4.6     2052     22  2011  Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Fiction  
3               George Orwell          4.7    21424      6  2017  Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Fiction  
..                        ...          ...      ...    ...   ...      ...  
546               Jen Sincero          4.7    14331      8  2016  Fiction  
547               Jen Sincero          4.7    14331      8  2017  Fiction  
548               Jen Sincero          4.7    14331      8  2018  Fiction  
549               Jen Sincero          4.7    14331      8  2019  Fiction  
0                    JJ Smith          4.7    17350      8  2016  Fiction  

[551 rows x 7 columns]

In [ ]:
df_books.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year    Genre  
0                    JJ Smith          4.7    17350      8  2016  Fiction  
1                Stephen King          4.6     2052     22  2011  Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Fiction  
3               George Orwell          4.7    21424      6  2017  Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Fiction  
..                        ...          ...      ...    ...   ...      ...  
545               Jeff Kinney          4.9     9413      8  2019  Fiction  
546               Jen Sincero          4.7    14331      8  2016  Fiction  
547               Jen Sincero          4.7    14331      8  2017  Fiction  
548               Jen Sincero          4.7    14331      8  2018  Fiction  
549               Jen Sincero          4.7    14331      8  2019  Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.sort_values('Year')

Name            Author  \
177                                      I, Alex Cross   James Patterson   
131  Glenn Beck's Common Sense: The Case Against an...        Glenn Beck   
417                                   The Last Lecture      Randy Pausch   
241                       New Moon (The Twilight Saga)   Stephenie Meyer   
72       Diary of a Wimpy Kid: The Last Straw (Book 3)       Jeff Kinney   
..                                                 ...               ...   
150                                               Guts  Raina Telgemeier   
466  The Subtle Art of Not Giving a F*ck: A Counter...       Mark Manson   
462                                 The Silent Patient  Alex Michaelides   
130  Girl, Wash Your Face: Stop Believing the Lies ...     Rachel Hollis   
549  You Are a Badass: How to Stop Doubting Your Gr...       Jen Sincero   

     User Rating  Reviews  Price  Year    Genre  
177          4.6     1320      7  2009  Fiction  
131          4.6     1365     11  2009  Fiction  
417          4.7     4028      9  2009  Fiction  
241          4.6     5680     10  2009  Fiction  
72           4.8     3837     15  2009  Fiction  
..           ...      ...    ...   ...      ...  
150          4.8     5476      7  2019  Fiction  
466          4.6    26490     15  2019  Fiction  
462          4.5    27536     14  2019  Fiction  
130          4.6    22288     12  2019  Fiction  
549          4.7    14331      8  2019  Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.sort_values('Year', ascending=False) # Del año más reciente al más antiguo.

Name                 Author  \
549  You Are a Badass: How to Stop Doubting Your Gr...            Jen Sincero   
294  School Zone - Big Preschool Workbook - Ages 4 ...            School Zone   
489                   The Wonderful Things You Will Be  Emily Winfield Martin   
263    P is for Potty! (Sesame Street) (Lift-the-Flap)        Naomi Kleinberg   
130  Girl, Wash Your Face: Stop Believing the Lies ...          Rachel Hollis   
..                                                 ...                    ...   
418  The Last Olympian (Percy Jackson and the Olymp...           Rick Riordan   
38           Breaking Dawn (The Twilight Saga, Book 4)        Stephenie Meyer   
92   Eat This, Not That! Thousands of Simple Food S...        David Zinczenko   
139  Good to Great: Why Some Companies Make the Lea...            Jim Collins   
299                                  Sookie Stackhouse       Charlaine Harris   

     User Rating  Reviews  Price  Year    Genre  
549          4.7    14331      8  2019  Fiction  
294          4.8    23047      6  2019  Fiction  
489          4.9     8842     10  2019  Fiction  
263          4.7    10820      5  2019  Fiction  
130          4.6    22288     12  2019  Fiction  
..           ...      ...    ...   ...      ...  
418          4.8     4628      7  2009  Fiction  
38           4.6     9769     13  2009  Fiction  
92           4.3      956     14  2009  Fiction  
139          4.5     3457     14  2009  Fiction  
299          4.7      973     25  2009  Fiction  

[550 rows x 7 columns]

#18 - Groupby

In [ ]:
df_books.groupby('Author').count() #Contar los libros que tiene cada autor

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [ ]:
df_books.groupby('Author').mean() # calcular la media de rating, reviews, precio y año por autor

User Rating       Reviews      Price         Year
Author                                                                       
Abraham Verghese               4.600000   4866.000000  11.000000  2010.500000
Adam Gasiewski                 4.400000   3113.000000   6.000000  2017.000000
Adam Mansbach                  4.800000   9568.000000   9.000000  2011.000000
Adir Levy                      4.800000   8170.000000  13.000000  2019.000000
Admiral William H. McRaven     4.700000  10199.000000  11.000000  2017.000000
...                                 ...           ...        ...          ...
Walter Isaacson                4.566667   6222.666667  20.333333  2013.333333
William Davis                  4.400000   7497.000000   6.000000  2012.500000
William P. Young               4.600000  19720.000000   8.000000  2013.000000
Wizards RPG Team               4.800000  16990.000000  27.000000  2018.000000
Zhi Gang Sha                   4.600000    128.500000  11.500000  2011.000000

[248 rows x 4 columns]

In [ ]:
df_books.groupby('Author')[['User Rating', 'Reviews', 'Price']].mean() # calcular la media de rating, reviews, precio por autor. No incluye el año.

User Rating       Reviews      Price
Author                                                          
Abraham Verghese               4.600000   4866.000000  11.000000
Adam Gasiewski                 4.400000   3113.000000   6.000000
Adam Mansbach                  4.800000   9568.000000   9.000000
Adir Levy                      4.800000   8170.000000  13.000000
Admiral William H. McRaven     4.700000  10199.000000  11.000000
...                                 ...           ...        ...
Walter Isaacson                4.566667   6222.666667  20.333333
William Davis                  4.400000   7497.000000   6.000000
William P. Young               4.600000  19720.000000   8.000000
Wizards RPG Team               4.800000  16990.000000  27.000000
Zhi Gang Sha                   4.600000    128.500000  11.500000

[248 rows x 3 columns]

In [ ]:
df_books.groupby('Author').min()

Name  \
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                            User Rating  Reviews  Price  Year    Genre  
Author                                                                  
Abraham Verghese                    4.6     4866     11  2010  Fiction  
Adam Gasiewski                      4.4     3113      6  2017  Fiction  
Adam Mansbach                       4.8     9568      9  2011  Fiction  
Adir Levy                           4.8     8170     13  2019  Fiction  
Admiral William H. McRaven          4.7    10199     11  2017  Fiction  
...                                 ...      ...    ...   ...      ...  
Walter Isaacson                     4.5     3014     20  2011  Fiction  
William Davis                       4.4     7497      6  2012  Fiction  
William P. Young                    4.6    19720      8  2009  Fiction  
Wizards RPG Team                    4.8    16990     27  2017  Fiction  
Zhi Gang Sha                        4.6       37      6  2009  Fiction  

[248 rows x 6 columns]

In [ ]:
df_books.groupby('Author').max()

Name  \
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                            User Rating  Reviews  Price  Year    Genre  
Author                                                                  
Abraham Verghese                    4.6     4866     11  2011  Fiction  
Adam Gasiewski                      4.4     3113      6  2017  Fiction  
Adam Mansbach                       4.8     9568      9  2011  Fiction  
Adir Levy                           4.8     8170     13  2019  Fiction  
Admiral William H. McRaven          4.7    10199     11  2017  Fiction  
...                                 ...      ...    ...   ...      ...  
Walter Isaacson                     4.6     7827     21  2017  Fiction  
William Davis                       4.4     7497      6  2013  Fiction  
William P. Young                    4.6    19720      8  2017  Fiction  
Wizards RPG Team                    4.8    16990     27  2019  Fiction  
Zhi Gang Sha                        4.6      220     17  2013  Fiction  

[248 rows x 6 columns]

In [ ]:
df_books.groupby('Author').sum()

User Rating  Reviews  Price  Year
Author                                                       
Abraham Verghese                    9.2     9732     22  4021
Adam Gasiewski                      4.4     3113      6  2017
Adam Mansbach                       4.8     9568      9  2011
Adir Levy                           4.8     8170     13  2019
Admiral William H. McRaven          4.7    10199     11  2017
...                                 ...      ...    ...   ...
Walter Isaacson                    13.7    18668     61  6040
William Davis                       8.8    14994     12  4025
William P. Young                    9.2    39440     16  4026
Wizards RPG Team                   14.4    50970     81  6054
Zhi Gang Sha                        9.2      257     23  4022

[248 rows x 4 columns]

In [ ]:
df_books.groupby('Author').sum().loc['William Davis']

User Rating        8.8
Reviews        14994.0
Price             12.0
Year            4025.0
Name: William Davis, dtype: float64

In [ ]:
df_books.groupby('Author').sum().reset_index()

Author  User Rating  Reviews  Price  Year
0              Abraham Verghese          9.2     9732     22  4021
1                Adam Gasiewski          4.4     3113      6  2017
2                 Adam Mansbach          4.8     9568      9  2011
3                     Adir Levy          4.8     8170     13  2019
4    Admiral William H. McRaven          4.7    10199     11  2017
..                          ...          ...      ...    ...   ...
243             Walter Isaacson         13.7    18668     61  6040
244               William Davis          8.8    14994     12  4025
245            William P. Young          9.2    39440     16  4026
246            Wizards RPG Team         14.4    50970     81  6054
247                Zhi Gang Sha          9.2      257     23  4022

[248 rows x 5 columns]

In [ ]:
df_books.groupby('Author')[['User Rating', 'Reviews', 'Price']].sum().reset_index()

Author  User Rating  Reviews  Price
0              Abraham Verghese          9.2     9732     22
1                Adam Gasiewski          4.4     3113      6
2                 Adam Mansbach          4.8     9568      9
3                     Adir Levy          4.8     8170     13
4    Admiral William H. McRaven          4.7    10199     11
..                          ...          ...      ...    ...
243             Walter Isaacson         13.7    18668     61
244               William Davis          8.8    14994     12
245            William P. Young          9.2    39440     16
246            Wizards RPG Team         14.4    50970     81
247                Zhi Gang Sha          9.2      257     23

[248 rows x 4 columns]

In [ ]:
df_books.groupby('Author').agg(['min', 'max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                    Genre           
                             max      min      max  
Author                                              
Abraham Verghese            2011  Fiction  Fiction  
Adam Gasiewski              2017  Fiction  Fiction  
Adam Mansbach               2011  Fiction  Fiction  
Adir Levy                   2019  Fiction  Fiction  
Admiral William H. McRaven  2017  Fiction  Fiction  
...                          ...      ...      ...  
Walter Isaacson             2017  Fiction  Fiction  
William Davis               2013  Fiction  Fiction  
William P. Young            2017  Fiction  Fiction  
Wizards RPG Team            2019  Fiction  Fiction  
Zhi Gang Sha         

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year    Genre  
0  2016  Fiction  
1  2011  Fiction

In [ ]:
df_books.groupby('Author').agg({'Reviews':['min', 'max'], 'User Rating':'sum'}) #Calcular por autor: min y max de la review, suma acumulativa del rating

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [ ]:
df_books.groupby(['Author', 'Year']).count()

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]

#19 - Combinando DataFrames
*Inner join* es sólo los registros que tengan columndas en común, en SQL serían donde la llave primaria de una tabla coincida con la llave foránea de la otra tabla donde haya una relación.
 *left join* hace lo de inner con el agregado de los datos de la primera tabla (del dataframe en este caso) que no tengan una relación con la otra tabla o dataframe.
 *rigth join* sería con la segunda tabla ó dataframe
 *outer join* juntaría todo, tengan relación o no.

**20-Merge, Join y Concat**

In [ ]:
df1 = pd.DataFrame({'A':['A0', 'A1', 'A2', 'A3'],
 'B':['B0', 'B1', 'B2', 'B3'],
 'C':['C0', 'C1', 'C2', 'C3'],
 'D':['D0', 'D1', 'D2', 'D3']
 })

df2 = pd.DataFrame({'A':['A4', 'A5', 'A6', 'A7'],
 'B':['B4', 'B5', 'B6', 'B7'],
 'C':['C4', 'C5', 'C6', 'C7'],
 'D':['D4', 'D5', 'D6', 'D7']
 })

In [ ]:
pd.concat([df1, df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
pd.concat([df1, df2], axis=0)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [ ]:
pd.concat([df1, df2], ignore_index=True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
pd.concat([df1, df2], axis=1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

**Merge**

In [ ]:
izq = pd.DataFrame({'key':['k0', 'k1', 'k2', 'k3'],
 'A':['A0', 'A1', 'A2', 'A3'],
 'B':['B0', 'B1', 'B2', 'B3']
 })

der = pd.DataFrame({'key':['k0', 'k1', 'k2', 'k3'],
 'C':['C0', 'C1', 'C2', 'C3'],
 'D':['D0', 'D1', 'D2', 'D3']
 })

In [ ]:
#Mezcla de dataframes
izq.merge(der, on='key') #onkey es para indicar la 'llave', la columna que tienen en común las tablas...

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

**¿Qué pasa si la columna por la cual queremos fusionar los dataframes tienen nombres diferentes aunque tengan los mismos datos?**

In [ ]:
izq = pd.DataFrame({'key':['k0', 'k1', 'k2', 'k3'],
 'A':['A0', 'A1', 'A2', 'A3'],
 'B':['B0', 'B1', 'B2', 'B3']
 })

der = pd.DataFrame({'key_2':['k0', 'k1', 'k2', 'k3'],
 'C':['C0', 'C1', 'C2', 'C3'],
 'D':['D0', 'D1', 'D2', 'D3']
 })

In [ ]:
izq.merge(der, left_on='key', right_on='key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2
3  k3  A3  B3    k3  C3  D3

In [ ]:
izq = pd.DataFrame({'key':['k0', 'k1', 'k2', 'k3'],
 'A':['A0', 'A1', 'A2', 'A3'],
 'B':['B0', 'B1', 'B2', 'B3']
 })

der = pd.DataFrame({'key_2':['k0', 'k1', 'k2', np.nan],
 'C':['C0', 'C1', 'C2', 'C3'],
 'D':['D0', 'D1', 'D2', 'D3']
 })

In [ ]:
der

key_2   C   D
0    k0  C0  D0
1    k1  C1  D1
2    k2  C2  D2
3   NaN  C3  D3

In [ ]:
izq.merge(der, left_on='key', right_on='key_2', how='left') # prioridad para los datos de la izquierda que no tienen match con los de la derecha

key   A   B key_2    C    D
0  k0  A0  B0    k0   C0   D0
1  k1  A1  B1    k1   C1   D1
2  k2  A2  B2    k2   C2   D2
3  k3  A3  B3   NaN  NaN  NaN

In [ ]:
izq.merge(der, left_on='key', right_on='key_2', how='right') # prioridad para los datos de la derecha que no tienen match con los de la izquierda

key    A    B key_2   C   D
0   k0   A0   B0    k0  C0  D0
1   k1   A1   B1    k1  C1  D1
2   k2   A2   B2    k2  C2  D2
3  NaN  NaN  NaN   NaN  C3  D3

In [ ]:
izq.merge(der, left_on='key', right_on='key_2', how='inner')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2

#21 - Join
*Join va a ir directamente a los índices con los que estemos trabajando en los DataFrames, no en las etiquetas de las columnas...*

In [ ]:
izq = pd.DataFrame({ 'A':['A0', 'A1', 'A2'],
 'B':['B0', 'B1', 'B2']}, 
 index=['k0', 'k1', 'k2'])
der = pd.DataFrame({ 'C':['C0', 'C1', 'C2'],
 'D':['D0', 'D1', 'D2']}, 
 index=['k0', 'k2', 'k3'])

In [ ]:
izq.join(der, how='inner')

A   B   C   D
k0  A0  B0  C0  D0
k2  A2  B2  C1  D1

In [ ]:
izq.join(der, how='left')

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1  NaN  NaN
k2  A2  B2   C1   D1

In [ ]:
izq.join(der, how='right')

A    B   C   D
k0   A0   B0  C0  D0
k2   A2   B2  C1  D1
k3  NaN  NaN  C2  D2

In [ ]:
izq.join(der, how='outer')

A    B    C    D
k0   A0   B0   C0   D0
k1   A1   B1  NaN  NaN
k2   A2   B2   C1   D1
k3  NaN  NaN   C2   D2

#22 - Pivot y Melt
**Pivot Table**

In [ ]:
df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [ ]:
df_books['Genre'].unique()

array(['Non Fiction', 'Fiction'], dtype=object)

In [ ]:
df_books['User Rating'].unique()

array([4.7, 4.6, 4.8, 4.4, 4.5, 3.9, 4.3, 4.2, 4.9, 3.8, 3.6, 4. , 4.1,
       3.3])

In [ ]:
df_books.pivot_table(index='Author',columns='Genre',values='User Rating')

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [ ]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='sum')

Year          2009   2010   2011   2012   2013   2014   2015   2016   2017  \
Genre                                                                        
Fiction      110.2   92.3   97.0   94.4  109.1  134.3   79.1   89.6  113.7   
Non Fiction  119.0  135.6  130.9  132.2  118.6   96.8  153.3  144.3  119.3   

Year          2018   2019  
Genre                      
Fiction       99.5   96.4  
Non Fiction  133.9  140.6

**Melt**

El método melt toma las columnas del DataFrame y las pasa a filas, con dos nuevas columnas para especificar la antigua columna y el valor que traía.

Por ejemplo, simplemente al imprimir las cinco primeras filas del DataFrame con las columnas de Name y Genre se tiene este resultado.

Para ello ejecuta la siguiente línea en tu Jupyter Notebook:

In [ ]:
df_books[['Name','Genre']].head(5)

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [ ]:
df_books[['Name','Genre']].head(5).melt()

variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

Ahora cada resultado de las dos columnas pasa a una fila de este modo a tipo llave:valor.

En el siguiente ejemplo ejecutemos melt de esta manera:

In [ ]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
545  2019    Genre      Fiction
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction

[550 rows x 3 columns]

Simplemente, podemos seleccionar las columnas que no quiero hacer melt usando el parámetro id_vars. Para este caso Year y también la única columna que quiero aplicar el melt, para este caso Genre con la propiedad value_vars.

#22 - Apply

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
def to_times(val):
  return val * 2

In [ ]:
df_books['User Rating'].apply(to_times)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ... 
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: User Rating, Length: 550, dtype: float64

In [ ]:
df_books['Rating_2'] = df_books['User Rating'].apply(to_times)

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Rating_2  
0         9.4  
1         9.2  
2         9.4  
3         9.4  
4         9.6  
..        ...  
545       9.8  
546       9.4  
547       9.4  
548       9.4  
549       9.4  

[550 rows x 8 columns]

In [ ]:
df_books['Rating_2'] = df_books['User Rating'].apply(lambda x: x*3)

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Rating_2  
0        14.1  
1        13.8  
2        14.1  
3        14.1  
4        14.4  
..        ...  
545      14.7  
546      14.1  
547      14.1  
548      14.1  
549      14.1  

[550 rows x 8 columns]

In [ ]:
df_books['Rating_2'] = df_books.apply(lambda x: x['User Rating'] * 2 if x['Genre'] == 'Fiction' else x['User Rating'], axis=1)
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Rating_2  
0         4.7  
1         9.2  
2         4.7  
3         9.4  
4         4.8  
..        ...  
545       9.8  
546       4.7  
547       4.7  
548       4.7  
549       4.7  

[550 rows x 8 columns]

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
df = pd.DataFrame({
    'edad' :     [ 10, 9, 13, 14, 12, 11, 12],
    'cm' : [ 115, 110, 130, 155, 125, 120, 125],
    'pais' :    [ 'co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
    'genero' :  [ 'F', 'M', 'M', 'M', 'F', 'F', 'F'],
    'Q1' : [ 5, 10, 8, np.nan, 7, 8, 3],
    'Q2' : [ 7, 9, 9, 8, 8, 8, 9.]
}, index = ['Ana','Benito','Camilo','Daniel','Erika','Paola','Gabriela']) 
df

edad   cm pais genero    Q1   Q2
Ana         10  115   co      F   5.0  7.0
Benito       9  110   mx      M  10.0  9.0
Camilo      13  130   co      M   8.0  9.0
Daniel      14  155   mx      M   NaN  8.0
Erika       12  125   mx      F   7.0  8.0
Paola       11  120   ch      F   8.0  8.0
Gabriela    12  125   ch      F   3.0  9.0

In [ ]:
df.groupby('genero')['cm'].agg([np.mean, np.std])

mean        std
genero                       
F       121.250000   4.787136
M       131.666667  22.546249

In [ ]:
df = pd.DataFrame({
    'edad' :     [ 10, 9, 13, 14, 12, 11, 12],
    'cm' : [ 115, 110, 130, 155, 125, 120, 125],
    'pais' :    [ 'co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
    'genero' :  [ 'F', 'M', 'M', 'M', 'F', 'F', 'F'],
    'Q1' : [ 5, 10, 8, np.nan, 7, 8, 3],
    'Q2' : [ 7, 9, 9, 8, 8, 8, 9.]
}, index = ['Ana','Benito','Camilo','Daniel','Erika','Paola','Gabriela'])

print(df.iloc[[4],[2]])

      pais
Erika   mx


In [ ]:
df = pd.DataFrame({
    'edad' :     [ 10, 9, 13, 14, 12, 11, 12],
    'cm' : [ 115, 110, 130, 155, 125, 120, 125],
    'pais' :    [ 'co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
    'genero' :  [ 'F', 'M', 'M', 'M', 'F', 'F', 'F'],
    'Q1' : [ 5, 10, 8, np.nan, 7, 8, 3],
    'Q2' : [ 7, 9, 9, 8, 8, 8, 9.]
}, index = ['Ana','Benito','Camilo','Daniel','Erika','Paola','Gabriela']) 

In [ ]:
df['edad'].mean()

11.571428571428571

In [ ]:
(10+11+12+12)/4

11.25

In [ ]:
df = pd.DataFrame({
    'edad' :     [ 10, 9, 13, 14, 12, 11, 12],
    'cm' : [ 115, 110, 130, 155, 125, 120, 125],
    'pais' :    [ 'co', 'mx', 'co', 'mx', 'mx', 'ch', 'ch'],
    'genero' :  [ 'F', 'M', 'M', 'M', 'F', 'F', 'F'],
    'Q1' : [ 5, 10, 8, np.nan, 7, 8, 3],
    'Q2' : [ 7, 9, 9, 8, 8, 8, 9.]
}, index = ['Ana','Benito','Camilo','Daniel','Erika','Paola','Gabriela'])


print(df.query("(edad >= 12) & (cm < 130) & (Q1 > 5)")['Q2'])

Erika    8.0
Name: Q2, dtype: float64


In [ ]:
[10,8,5,0] + [0,1,6,12]

[10, 8, 5, 0, 0, 1, 6, 12]

In [ ]:
pd.NA | False

<NA>